### ISSUE TITLE
Pull image on remote node failed

### ISSUE THREAD

**Issue by jofrey007** [vjuranek/docker-build-step-plugin#64] opened 2021-02-10 09:58 UTC
We are running docker on another node with custom docker registry in intranet network.
When executing job with this Docker command 
![image](https://user-images.githubusercontent.com/51148288/107494220-cf288780-6b8e-11eb-8710-fe832f1d3432.png)

we got this error message 

Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building remotely on docker-server (Docker) in workspace /home/rsys/jenkins/sharedspace/projects
[Docker] INFO: Pulling image registry.irsys.sk/slpd_build:200929
[Docker] ERROR: failed to pull image registry.irsys.sk/slpd_build:200929
ERROR: Build step failed with exception
java.lang.NullPointerException
 at org.glassfish.hk2.utilities.ServiceLocatorUtilities.enablePerThreadScope(ServiceLocatorUtilities.java:112)
 at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:141)
 at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
 at org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:63)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at java.lang.Class.newInstance(Class.java:584)
 at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:118)
Caused: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated
 at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:122)
 at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:225)
 at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
Also: hudson.remoting.Channel$CallSiteStackTrace: Remote call to docker-server
 at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
 at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
 at hudson.remoting.Channel.call(Channel.java:1001)
 at org.jenkinsci.plugins.dockerbuildstep.cmd.PullImageCommand.execute(PullImageCommand.java:80)
 at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder.perform(DockerBuilder.java:77)
 at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
 at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
 at hudson.model.Build$BuildExecution.build(Build.java:197)
 at hudson.model.Build$BuildExecution.doRun(Build.java:163)
 at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
 at hudson.model.Run.execute(Run.java:1907)
 at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
 at hudson.model.ResourceController.execute(ResourceController.java:97)
 at hudson.model.Executor.run(Executor.java:429)
Caused: java.lang.RuntimeException
 at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
 at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
 at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
 at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
 at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:71)
 at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:290)
 at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:76)
 at com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory.init(JerseyDockerCmdExecFactory.java:234)
 at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:161)
 at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)
 at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder$DescriptorImpl.createDockerClient(DockerBuilder.java:143)
 at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder$DescriptorImpl.getDockerClient(DockerBuilder.java:229)
 at org.jenkinsci.plugins.dockerbuildstep.cmd.DockerCommand.getClient(DockerCommand.java:100)
 at org.jenkinsci.plugins.dockerbuildstep.cmd.remote.PullImageRemoteCallable.call(PullImageRemoteCallable.java:48)
 at org.jenkinsci.plugins.dockerbuildstep.cmd.remote.PullImageRemoteCallable.call(PullImageRemoteCallable.java:26)
 at hudson.remoting.UserRequest.perform(UserRequest.java:211)
 at hudson.remoting.UserRequest.perform(UserRequest.java:54)
 at hudson.remoting.Request$2.run(Request.java:375)
 at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.lang.Thread.run(Thread.java:834)
Caused: java.lang.IllegalArgumentException
 at org.jenkinsci.plugins.dockerbuildstep.cmd.PullImageCommand.execute(PullImageCommand.java:85)
 at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder.perform(DockerBuilder.java:77)
 at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
 at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
 at hudson.model.Build$BuildExecution.build(Build.java:197)
 at hudson.model.Build$BuildExecution.doRun(Build.java:163)
 at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
 at hudson.model.Run.execute(Run.java:1907)
 at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
 at hudson.model.ResourceController.execute(ResourceController.java:97)
 at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute Docker command' marked build as failure
Finished: FAILURE
REST API

May you help us ?

**Comment by vjuranek** [comment] 2021-02-12 08:13
It looks like an issue with project dependencies. Unfortunately this plugin depends on Jersey (which can cause issue on different app servers) due to transitive dependency on docker-java. On which application server do you run Jenkins (and which version)?

**Comment by jofrey007** [comment] 2021-02-12 10:18
We are running Jenkins on archlinux virtual machine as a service
/usr/lib/jvm/java-8-openjdk/jre/bin/java -Xmx512m -jar /usr/share/java/jenkins/jenkins.war

java.version	1.8.0_275
Jenkins 2.263.2

**Comment by vjuranek** [comment] 2021-02-22 09:59
Thanks, I was able to reproduce. It seems to be related to https://www.jenkins.io/blog/2018/03/15/jep-200-lts/ but needs more investigation.

**Comment by vjuranek** [comment] 2021-02-22 20:43
> It seems to be related to https://www.jenkins.io/blog/2018/03/15/jep-200-lts/ but needs more investigation.

this assumptions seems to be wrong, still fails also with `-Djenkins.security.ClassFilterImpl.SUPPRESS_ALL=true`

**Comment by ParadoxShmaradox** [comment] 2021-03-21 13:43
Is there an update to this?
We just update Jenkins to the 2.277.1 from the previous lts and update all the plugins.
We have one node that's fine and another that displays this behavior.
Both nodes are connected via ssh and the Jenkins master is using the official docker image.

Going back to previous version 2.263.4 and downgrading plugins doesn't seem to work.

**Comment by jofrey007** [comment] 2021-03-23 07:03
We also updated Jenkins to LTS 2.277.1, update all plugins. 
Problem is still there.

**Comment by vjuranek** [comment] 2021-04-13 10:34
should be fixed (quickly tested on my seems to work fine) with jenkinsci/docker-build-step-plugin PR #76. Thanks @ParadoxShmaradox ! Released in v 2.7.

**Closed as completed by vjuranek** 2021-04-13 10:34 UTC
